version: '3.8'

services:

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
    depends_on:
      - microservice1
      - microservice2
  microservice1:
    build: microservice1
    container_name: microservice1
    ports:
      - "8081:8081"

  microservice2:
    build: microservice2
    container_name: microservice2
    ports:
      - "8082:8082"
    



